FROM cicca/anaconda:base
MAINTAINER Rick Moore

RUN apt-get update && apt-get install -y vim
RUN mkdir -p /opt/gddtool_pkg
RUN mkdir -p /app_data
COPY tools/XXXput.date.hereXXX /opt/tool_pkg
ENV PYTHONPATH=/opt/gddtool_pkg:$PYTHONPATH

EXPOSE 20004
CMD [ "/bin/bash" ]
