{ "{{button_labels}}":"{{ button_labels }}",
  "{{chart_labels}}":"{{ chart_labels }}",
  "{{chart_types}}":"{{ chart_types }}",
  "{{csftool_url}}":"{{ csftool_url }}",
  "{{max_year}}":"{{ max_year }}",
  "{{min_year}}":"{{ max_year }}",
  "{{season_description}}":"{{ season_description }}",
  "{{server_url}}":"{{ server_url }}",
  "{{tool_url}}":"{{ tool_url }}",
  "{{default_plant_day}}":"{{ default_plant_day }}",
  "{{season_end_day}}":"{{ season_end_day }}",
  "{{season_start_day}}":"{{ season_start_day }}",
  "{{gdd_threshold}}":"{{ gdd_threshold }}",
  "{{location_key}}":"{{ location_key }}",
  "{{location_address}}":"{{ location_address }}",
  "{{location_lat}}":"{{ location_lat }}",
  "{{location_lon}}":"{{ location_lon }}",
  "{{season}}":"{{ season }}",
}
